//! pprof.proto exporter.
//!
//! Renders `SpanTree` as a Google pprof.proto Profile, gzipped.
//! Compatible with `go tool pprof`, Pyroscope, Grafana Profiles,
//! and the OTel Profile signal.
//!
//! Sample types (one per ValueType):
//! - `wall` (microseconds) — `(end_ns - start_ns) / 1000`
//! - `cpu`  (microseconds) — `cpu_ns / 1000`
//! - `alloc_space` (bytes) — `max(0, mem_exit - mem_enter)`
//! - `inuse_space` (bytes) — `max(0, mem_peak - mem_enter)`
//!
//! One sample per leaf span; the stack trace is the parent chain
//! (leaf-first ordering per pprof convention). Span attributes
//! become per-sample labels.

#![allow(clippy::all)] // keep generated proto-derived code happy

#[allow(dead_code)]
mod proto {
    // Generated by build.rs / prost-build from proto/pprof.proto.
    // Many of the fields / variants aren't used by the exporter and
    // dead_code is the expected state for the unused ones.
    include!(concat!(env!("OUT_DIR"), "/perftools.profiles.rs"));
}

use std::collections::{HashMap, HashSet};
use std::io::Write;
use std::sync::Arc;

use flate2::write::GzEncoder;
use flate2::Compression;
use prost::Message;

use crate::profiling::{FinishedSpan, SpanTree};

/// String-table interner. Index 0 reserved for the empty string per
/// pprof convention; new strings get appended and their index returned
/// (cast to `i64` for pprof's signed-type slots).
///
/// `table` and `by_str` share ownership of each interned string via
/// `Arc<str>`, so a miss costs a single heap allocation (plus an
/// atomic refcount bump for the `table` push) instead of the two
/// `String::to_string()` copies the earlier version did.
struct StringInterner {
    table: Vec<Arc<str>>,
    by_str: HashMap<Arc<str>, i64>,
}

impl StringInterner {
    fn new() -> Self {
        let mut s = Self {
            table: Vec::new(),
            by_str: HashMap::new(),
        };
        s.intern(""); // index 0
        s
    }

    fn intern(&mut self, value: &str) -> i64 {
        if let Some(&i) = self.by_str.get(value) {
            return i;
        }
        let owned: Arc<str> = Arc::from(value);
        let i = self.table.len() as i64;
        self.table.push(Arc::clone(&owned));
        self.by_str.insert(owned, i);
        i
    }
}

fn build_value_types(strings: &mut StringInterner) -> Vec<proto::ValueType> {
    let bytes_unit = strings.intern("bytes");
    let micros_unit = strings.intern("microseconds");
    vec![
        proto::ValueType {
            r#type: strings.intern("wall"),
            unit: micros_unit,
        },
        proto::ValueType {
            r#type: strings.intern("cpu"),
            unit: micros_unit,
        },
        proto::ValueType {
            r#type: strings.intern("alloc_space"),
            unit: bytes_unit,
        },
        proto::ValueType {
            r#type: strings.intern("inuse_space"),
            unit: bytes_unit,
        },
    ]
}

/// Intern a function name, returning the 1-based id reused by both
/// the Function and the Location entries (one Line per Location).
fn intern_function(
    name: &str,
    strings: &mut StringInterner,
    function_ids: &mut HashMap<String, u64>,
    functions: &mut Vec<proto::Function>,
    locations: &mut Vec<proto::Location>,
) -> u64 {
    if let Some(&id) = function_ids.get(name) {
        return id;
    }
    let id = (functions.len() as u64) + 1;
    let name_idx = strings.intern(name);
    functions.push(proto::Function {
        id,
        name: name_idx,
        system_name: name_idx,
        filename: 0,
        start_line: 0,
    });
    locations.push(proto::Location {
        id,
        mapping_id: 1,
        address: 0,
        line: vec![proto::Line {
            function_id: id,
            line: 0,
            column: 0,
        }],
        is_folded: false,
    });
    function_ids.insert(name.to_string(), id);
    id
}

/// Render the tree as gzipped pprof.proto bytes.
///
/// Content-Type: `application/vnd.google.pprof+proto+gzip`.
pub fn export_pprof(tree: &SpanTree) -> Vec<u8> {
    let mut strings = StringInterner::new();
    let sample_types = build_value_types(&mut strings);

    // Build span_id → &FinishedSpan plus the parent-id set for leaf
    // detection. A span is a leaf iff its span_id is NOT in any
    // other span's parent_span_id.
    let mut by_id: HashMap<&str, &FinishedSpan> = HashMap::with_capacity(tree.finished.len());
    let mut parent_ids: HashSet<&str> = HashSet::with_capacity(tree.finished.len());
    for s in &tree.finished {
        by_id.insert(s.span_id.as_ref(), s);
        parent_ids.insert(s.parent_span_id.as_ref());
    }

    let mut function_ids: HashMap<String, u64> = HashMap::new();
    let mut functions: Vec<proto::Function> = Vec::new();
    let mut locations: Vec<proto::Location> = Vec::new();
    let mut samples: Vec<proto::Sample> = Vec::new();

    for span in &tree.finished {
        // Skip non-leaf spans — only leaves contribute samples per
        // pprof convention (intermediates would double-count when
        // tooling sums per-function totals).
        if parent_ids.contains(span.span_id.as_ref()) {
            continue;
        }

        // Walk parent chain leaf → root. chain_names is leaf-first
        // already, which matches pprof's location_id ordering ("leaf
        // is at location_id[0]" per the .proto comment).
        let mut chain_names: Vec<&str> = Vec::with_capacity(8);
        chain_names.push(span.name.as_ref());
        let mut cur: &FinishedSpan = span;
        while cur.parent_span_id != tree.root_span_id {
            match by_id.get(cur.parent_span_id.as_ref()) {
                Some(parent) => {
                    chain_names.push(parent.name.as_ref());
                    cur = parent;
                }
                None => break, // orphan — stop walking
            }
        }
        let location_id: Vec<u64> = chain_names
            .iter()
            .map(|n| {
                intern_function(
                    n,
                    &mut strings,
                    &mut function_ids,
                    &mut functions,
                    &mut locations,
                )
            })
            .collect();

        let wt_us = span.end_ns.saturating_sub(span.start_ns) / 1000;
        let cpu_us = span.cpu_ns / 1000;
        let alloc = (span.mem_exit - span.mem_enter).max(0);
        let inuse = (span.mem_peak - span.mem_enter).max(0);

        let labels: Vec<proto::Label> = span
            .attributes
            .iter()
            .map(|(k, v)| proto::Label {
                key: strings.intern(k),
                str: strings.intern(v),
                num: 0,
                num_unit: 0,
            })
            .collect();

        samples.push(proto::Sample {
            location_id,
            value: vec![wt_us as i64, cpu_us as i64, alloc, inuse],
            label: labels,
        });
    }

    // Profile timing window — same min/max as speedscope. now_ns()
    // is SystemTime nanos so meaningful as time_nanos.
    let (time_nanos, duration_nanos) = if tree.finished.is_empty() {
        (0, 0)
    } else {
        let mut min_start = u64::MAX;
        let mut max_end = 0u64;
        for s in &tree.finished {
            if s.start_ns < min_start {
                min_start = s.start_ns;
            }
            if s.end_ns > max_end {
                max_end = s.end_ns;
            }
        }
        (min_start as i64, max_end.saturating_sub(min_start) as i64)
    };

    let default_sample_type = strings.intern("wall");

    let profile = proto::Profile {
        sample_type: sample_types,
        sample: samples,
        mapping: vec![proto::Mapping {
            id: 1,
            ..Default::default()
        }],
        location: locations,
        function: functions,
        string_table: strings.table.iter().map(|s| s.to_string()).collect(),
        drop_frames: 0,
        keep_frames: 0,
        time_nanos,
        duration_nanos,
        period_type: None,
        period: 0,
        comment: vec![],
        default_sample_type,
        doc_url: 0,
    };

    let raw = profile.encode_to_vec();

    // level 1 (fastest) — profile bytes are ephemeral (local disk +
    // HTTP push), level 6 is wasted CPU on the hot export path.
    let mut gz = GzEncoder::new(Vec::with_capacity(raw.len() / 2), Compression::fast());
    gz.write_all(&raw).expect("gzip write should not fail");
    gz.finish().expect("gzip finish should not fail")
}
